project_id = "uolpwcngftpmgkopltwz"

[functions.csp-reporter]
verify_jwt = false

[functions.generate-timeline-image]
verify_jwt = false

[functions.seed-admin-user]
verify_jwt = false

[functions.geofence-processor]
verify_jwt = false