-- Seed catalog.* from a one-off local RewardsCcCatalogSync snapshot (generated by dump_local_catalog.sql).
-- Catalog is normally runtime-loaded by the worker from the paid RewardsCC API; prod is still in testing,
-- so this snapshot is applied as a regular seed via run-all.sql / supabase-migrate (prod adopts the
-- list-all-cards API later). Included from run-all.sql at the catalog seed slot — before the FSQ bridge.
--
-- \copy paths are relative to psql's CWD, so run from the REPO ROOT (how run-all.sql / supabase-migrate
-- run it). Standalone: psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase/seeds/catalog_snapshot.sql
--
-- Idempotent:
--   * issuers / categories / products / aliases — upsert on their business code (re-runnable).
--   * reward_rules have no natural key, so they are fully replaced for every seeded product
--     (delete-by-product then insert) — re-running converges to the snapshot.
-- Every FK is resolved by code against the target DB's own rows, so local/prod identity ids may differ.
-- Prereqs (already seeded earlier in run-all.sql): lookup.card_networks, lookup.reward_currencies,
-- lookup.cap_periods, and the catalog schema (migrations/catalog.sql).

\set ON_ERROR_STOP on

begin;

-- Stage everything as text; cast on insert so empty CSV fields become NULL cleanly.
create temp table _stage_issuers (
  code text, display_name text, logo_url text, is_active text, rewardscc_id text
) on commit drop;
create temp table _stage_categories (
  code text, display_name text, icon text, provider_category_id text,
  category_group text, subcategory_group text, is_active text
) on commit drop;
create temp table _stage_products (
  code text, issuer_code text, network_code text, reward_currency_code text,
  display_name text, card_art_url text, annual_fee text, purchase_apr text,
  foreign_transaction_fee text, terms_summary text, reward_currency_name text,
  base_reward_rate text, rewardscc_id text, card_type text, card_url text, fx_fee text,
  credit_range text, base_reward_valuation text, has_lounge_access text,
  has_free_checked_bag text, has_trusted_traveler_credit text, has_free_hotel_night text,
  signup_bonus text, perks text, annual_spend_rewards text, is_active text
) on commit drop;
create temp table _stage_aliases (
  category_code text, alias text, source text
) on commit drop;
create temp table _stage_rules (
  card_product_code text, category_code text, multiplier text, cap_amount text,
  cap_period_code text, start_date text, end_date text, requires_activation text,
  is_merchant_locked text, merchant_brand text, notes text
) on commit drop;

\copy _stage_issuers    from 'supabase/seeds/data/catalog_card_issuers.csv'    with (format csv, header true)
\copy _stage_categories from 'supabase/seeds/data/catalog_categories.csv'      with (format csv, header true)
\copy _stage_products   from 'supabase/seeds/data/catalog_card_products.csv'   with (format csv, header true)
\copy _stage_aliases    from 'supabase/seeds/data/catalog_category_aliases.csv' with (format csv, header true)
\copy _stage_rules      from 'supabase/seeds/data/catalog_reward_rules.csv'     with (format csv, header true)

-- 1. Issuers — upsert on code.
insert into catalog.card_issuers (code, display_name, logo_url, is_active, rewardscc_id)
select code, display_name, nullif(logo_url, ''), coalesce(nullif(is_active, '')::boolean, true),
       nullif(rewardscc_id, '')
from _stage_issuers
on conflict (code) do update set
  display_name = excluded.display_name,
  logo_url     = excluded.logo_url,
  is_active    = excluded.is_active,
  rewardscc_id = excluded.rewardscc_id,
  updated_at   = now();

-- 2. Categories — upsert on code.
insert into catalog.categories
  (code, display_name, icon, provider_category_id, category_group, subcategory_group, is_active)
select code, display_name, nullif(icon, ''), nullif(provider_category_id, ''),
       nullif(category_group, ''), nullif(subcategory_group, ''),
       coalesce(nullif(is_active, '')::boolean, true)
from _stage_categories
on conflict (code) do update set
  display_name      = excluded.display_name,
  icon              = excluded.icon,
  provider_category_id = excluded.provider_category_id,
  category_group    = excluded.category_group,
  subcategory_group = excluded.subcategory_group,
  is_active         = excluded.is_active,
  updated_at        = now();

-- 3. Products — resolve issuer/network/currency by code; upsert on code.
insert into catalog.card_products
  (issuer_id, network_id, reward_currency_id, code, display_name, card_art_url, annual_fee,
   purchase_apr, foreign_transaction_fee, terms_summary, reward_currency_name, base_reward_rate,
   rewardscc_id, card_type, card_url, fx_fee, credit_range, base_reward_valuation,
   has_lounge_access, has_free_checked_bag, has_trusted_traveler_credit, has_free_hotel_night,
   signup_bonus, perks, annual_spend_rewards, is_active)
select
  i.id, n.id, rc.id, s.code, s.display_name, nullif(s.card_art_url, ''),
  nullif(s.annual_fee, '')::numeric, nullif(s.purchase_apr, ''),
  nullif(s.foreign_transaction_fee, ''), nullif(s.terms_summary, ''),
  nullif(s.reward_currency_name, ''), coalesce(nullif(s.base_reward_rate, '')::numeric, 1.0),
  nullif(s.rewardscc_id, ''), nullif(s.card_type, ''), nullif(s.card_url, ''),
  nullif(s.fx_fee, '')::numeric, nullif(s.credit_range, ''),
  nullif(s.base_reward_valuation, '')::numeric,
  coalesce(nullif(s.has_lounge_access, '')::boolean, false),
  coalesce(nullif(s.has_free_checked_bag, '')::boolean, false),
  coalesce(nullif(s.has_trusted_traveler_credit, '')::boolean, false),
  coalesce(nullif(s.has_free_hotel_night, '')::boolean, false),
  nullif(s.signup_bonus, '')::jsonb, nullif(s.perks, '')::jsonb,
  nullif(s.annual_spend_rewards, '')::jsonb,
  coalesce(nullif(s.is_active, '')::boolean, true)
from _stage_products s
join catalog.card_issuers i on i.code = s.issuer_code
join lookup.card_networks n on n.code = s.network_code
join lookup.reward_currencies rc on rc.code = s.reward_currency_code
on conflict (code) do update set
  issuer_id = excluded.issuer_id,
  network_id = excluded.network_id,
  reward_currency_id = excluded.reward_currency_id,
  display_name = excluded.display_name,
  card_art_url = excluded.card_art_url,
  annual_fee = excluded.annual_fee,
  purchase_apr = excluded.purchase_apr,
  foreign_transaction_fee = excluded.foreign_transaction_fee,
  terms_summary = excluded.terms_summary,
  reward_currency_name = excluded.reward_currency_name,
  base_reward_rate = excluded.base_reward_rate,
  rewardscc_id = excluded.rewardscc_id,
  card_type = excluded.card_type,
  card_url = excluded.card_url,
  fx_fee = excluded.fx_fee,
  credit_range = excluded.credit_range,
  base_reward_valuation = excluded.base_reward_valuation,
  has_lounge_access = excluded.has_lounge_access,
  has_free_checked_bag = excluded.has_free_checked_bag,
  has_trusted_traveler_credit = excluded.has_trusted_traveler_credit,
  has_free_hotel_night = excluded.has_free_hotel_night,
  signup_bonus = excluded.signup_bonus,
  perks = excluded.perks,
  annual_spend_rewards = excluded.annual_spend_rewards,
  is_active = excluded.is_active,
  updated_at = now();

-- 4. Category aliases — resolve category by code; upsert on (category_id, alias).
insert into catalog.category_aliases (category_id, alias, source)
select c.id, s.alias, nullif(s.source, '')
from _stage_aliases s
join catalog.categories c on c.code = s.category_code
on conflict (category_id, alias) do update set source = excluded.source;

-- 5. Reward rules — no natural key. Replace all rules for the seeded products, then insert.
delete from catalog.reward_rules
where card_product_id in (
  select id from catalog.card_products
  where code in (select distinct card_product_code from _stage_rules)
);

insert into catalog.reward_rules
  (card_product_id, category_id, multiplier, cap_amount, cap_period_id, start_date, end_date,
   requires_activation, is_merchant_locked, merchant_brand, notes)
select
  p.id, c.id, s.multiplier::numeric, nullif(s.cap_amount, '')::numeric, cp.id,
  nullif(s.start_date, '')::date, nullif(s.end_date, '')::date,
  coalesce(nullif(s.requires_activation, '')::boolean, false),
  coalesce(nullif(s.is_merchant_locked, '')::boolean, false),
  nullif(s.merchant_brand, ''), nullif(s.notes, '')
from _stage_rules s
join catalog.card_products p on p.code = s.card_product_code
left join catalog.categories c on c.code = nullif(s.category_code, '')
left join lookup.cap_periods cp on cp.code = nullif(s.cap_period_code, '');

commit;

-- Report.
select
  (select count(*) from catalog.card_issuers)  as issuers,
  (select count(*) from catalog.categories)    as categories,
  (select count(*) from catalog.card_products) as products,
  (select count(*) from catalog.category_aliases) as aliases,
  (select count(*) from catalog.reward_rules)  as reward_rules;
