with target as (
  select id, code from catalog.categories
)
insert into catalog.category_aliases (category_id, alias, source)
select t.id, alias, 'seed' from target t
join (values
  ('electronics', 'electronics'),
  ('electronics', 'best buy'),
  ('electronics', 'apple store'),
  ('electronics', 'microcenter'),
  ('electronics', 'micro center'),
  ('electronics', 'b&h'),
  ('groceries', 'grocery'),
  ('groceries', 'groceries'),
  ('groceries', 'market'),
  ('groceries', 'supermarket'),
  ('groceries', 'whole foods'),
  ('groceries', 'trader joe'),
  ('groceries', 'safeway'),
  ('groceries', 'kroger'),
  ('groceries', 'walmart'),
  ('groceries', 'target'),
  ('groceries', 'aldi'),
  ('groceries', 'costco'),
  ('groceries', 'sams club'),
  ('clothing', 'clothing'),
  ('clothing', 'apparel'),
  ('clothing', 'h&m'),
  ('clothing', 'uniqlo'),
  ('clothing', 'gap'),
  ('clothing', 'zara'),
  ('clothing', 'old navy'),
  ('clothing', 'nordstrom'),
  ('clothing', 'macy'),
  ('clothing', 'target'),
  ('clothing', 'walmart'),
  ('home_goods', 'home goods'),
  ('home_goods', 'homegoods'),
  ('home_goods', 'ikea'),
  ('home_goods', 'home depot'),
  ('home_goods', 'lowes'),
  ('home_goods', 'bed bath'),
  ('home_goods', 'target'),
  ('home_goods', 'walmart'),
  ('beauty', 'beauty'),
  ('beauty', 'sephora'),
  ('beauty', 'ulta'),
  ('beauty', 'cosmetics'),
  ('beauty', 'target'),
  ('dining', 'dining'),
  ('dining', 'restaurant'),
  ('dining', 'cafe'),
  ('dining', 'coffee'),
  ('dining', 'starbucks'),
  ('dining', 'chipotle'),
  ('dining', 'mcdonald'),
  ('dining', 'pizza'),
  ('dining', 'sushi'),
  ('dining', 'kitchen'),
  ('dining', 'grill'),
  ('travel', 'travel'),
  ('travel', 'hotel'),
  ('travel', 'airline'),
  ('travel', 'airbnb'),
  ('travel', 'expedia'),
  ('travel', 'marriott'),
  ('travel', 'hilton'),
  ('travel', 'delta'),
  ('travel', 'united'),
  ('travel', 'american airlines')
) as src(category_code, alias) on src.category_code = t.code
on conflict (category_id, alias) do nothing;
