insert into lookup.event_types (code, display_name, severity) values
  ('pull_completed',                          'Pull Completed',                'info'),
  ('push_completed',                          'Push Completed',                'info'),
  ('conflict_detected',                       'Conflict Detected',             'warning'),
  ('conflict_resolved',                       'Conflict Resolved',             'info'),
  ('retry_scheduled',                         'Retry Scheduled',               'warning'),
  ('sync_failed',                             'Sync Failed',                   'error'),
  ('reconnect_needed',                        'Reconnect Needed',              'error'),
  ('messaging.notification.created',          'Notification Created',          'info'),
  ('messaging.notification.read',             'Notification Read',             'info'),
  ('messaging.notifications.read_all',        'Notifications Read All',        'info'),
  ('messaging.notification_preferences.updated',     'Notification Preferences Updated',     'info'),
  ('messaging.notification_type_preference.updated', 'Notification Type Preference Updated', 'info'),
  ('finance.user_card.created',               'User Card Created',             'info'),
  ('finance.user_card.updated',               'User Card Updated',             'info'),
  ('finance.user_card.deleted',               'User Card Deleted',             'info'),
  ('finance.reward_override.upserted',        'Reward Override Upserted',      'info'),
  ('finance.reward_override.deleted',         'Reward Override Deleted',       'info'),
  ('finance.plaid_connection.synced',         'Plaid Connection Synced',       'info'),
  ('finance.plaid_connection.disconnected',   'Plaid Connection Disconnected', 'info'),
  ('catalog.card_product_request.created',    'Card Product Request Created',  'info'),
  ('finance.transaction.created',             'Transaction Created',           'info'),
  ('finance.transaction.updated',             'Transaction Updated',           'info'),
  ('finance.transaction.deleted',             'Transaction Deleted',           'info'),
  ('finance.transaction.imported',            'Transaction Imported',          'info'),
  ('finance.missed_reward.not_a_miss',        'Missed Reward Not A Miss',      'info'),
  ('finance.missed_reward_event.created',     'Missed Reward Event Created',   'info'),
  ('finance.plaid_item.status_changed',       'Plaid Item Status Changed',     'warning'),
  ('finance.plaid_item.new_accounts_available','Plaid New Accounts Available', 'info'),
  ('insights.ai_generation.completed',        'AI Generation Completed',       'info')
on conflict (code) do update
  set display_name = excluded.display_name,
      severity     = excluded.severity;
