export const QueryKeys = {
  AuthBootstrap: ["auth", "bootstrap"] as const,
  Cards: ["cards"] as const,
  CardLimits: ["cards", "limits"] as const,
  CardDetail: (id: number) => ["cards", id] as const,
  CardRewardOverrides: (cardId: number) => ["cards", cardId, "reward-overrides"] as const,
  PlaidConnections: ["plaid", "connections"] as const,
  PlaidResyncQuota: ["plaid", "resync-quota"] as const,
  CatalogIssuers: ["catalog", "issuers"] as const,
  CatalogProducts: ["catalog", "products"] as const,
  CatalogCategories: ["catalog", "categories"] as const,
  HomeRecommendation: ["home", "recommendation"] as const,
  InStoreRecommendation: (merchantId: number, categoryCode?: string) =>
    ["recommendation", "in-store", merchantId, categoryCode ?? "any"] as const,
  OnboardingState: ["onboarding"] as const,
  BillingPlans: ["billing", "plans"] as const,
  BillingPrices: (countryCode: string) => ["billing", "prices", countryCode] as const,
  BillingFeatures: ["billing", "features"] as const,
  BillingSubscription: ["billing", "subscription"] as const,
  BillingPaymentMethods: ["billing", "payment-methods"] as const,
  Entitlements: ["entitlements"] as const,
  NotificationSettings: ["notification-settings"] as const,
  NotificationTypes: ["notification-settings", "types"] as const,
  Permissions: ["permissions"] as const,
  Transactions: (filters?: { q?: string; categoryCode?: string; cardId?: number }) =>
    filters ? ["transactions", filters] as const : ["transactions"] as const,
  TransactionDetail: (id: number) => ["transactions", id] as const,
  TransactionCategories: ["transactions", "categories"] as const,
  MissedRewards: ["transactions", "missed-rewards"] as const,
  Notifications: (filter?: string) => filter ? ["notifications", filter] as const : ["notifications"] as const,
  NotificationDetail: (id: number) => ["notifications", id] as const,
  NotificationReminders: ["notification-reminders"] as const,
  RewardsSummary: (period: string) => ["analytics", "rewards-summary", period] as const,
  MissedRewardsSummary: (period: string) => ["analytics", "missed-rewards-summary", period] as const,
  AIInsights: ["ai-insights"] as const,
  Profile: ["profile"] as const,
  Preferences: ["preferences"] as const,
  LookupsCurrencies: ["lookups", "currencies"] as const,
  LookupsPermissionStates: ["lookups", "permission-states"] as const,
  PrivacySettings: ["privacy", "settings"] as const,
  AccountDeletionStatus: ["privacy", "account-deletion"] as const,
  SyncStatus: ["sync", "status"] as const
};
