import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { AlertCircle } from "lucide-react";

export default function AIRecommendationPolicy() {
  return (
    <div className="min-h-screen bg-background py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <Card>
          <CardHeader>
            <CardTitle className="text-3xl font-bold text-primary">AI Recommendations & Limitations Policy</CardTitle>
            <p className="text-sm text-muted-foreground mt-2">Version 1.0 | Last updated: January 20, 2025</p>
          </CardHeader>
          <CardContent className="space-y-6">
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                This policy is provided for general informational purposes and does not constitute legal advice. 
                You should consult with your own legal counsel before relying on this document.
              </AlertDescription>
            </Alert>

            <section id="introduction">
              <h2 className="text-2xl font-semibold text-foreground mb-3">1. Overview of AI Use in TrueSpend</h2>
              <p className="text-foreground leading-relaxed mb-3">
                TrueSpend leverages artificial intelligence (AI), machine learning (ML), and advanced algorithms to analyze your spending data 
                and provide personalized insights, recommendations, and predictions. This AI Recommendations & Limitations Policy explains:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>How AI is used within the Service</li>
                <li>The types of recommendations and insights generated by AI</li>
                <li>The limitations and potential inaccuracies of AI outputs</li>
                <li>Your responsibility when using AI-generated recommendations</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3 font-semibold">
                By using the Service, you acknowledge that AI-generated content is probabilistic, may contain errors, and should not be 
                relied upon as the sole basis for financial decisions.
              </p>
            </section>

            <Separator />

            <section id="how-ai-is-used">
              <h2 className="text-2xl font-semibold text-foreground mb-3">2. How AI is Used in TrueSpend</h2>
              <p className="text-foreground leading-relaxed mb-3">
                TrueSpend employs AI and machine learning models in the following areas:
              </p>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">2.1 Transaction Categorization</h3>
              <p className="text-foreground leading-relaxed mb-3">
                AI algorithms automatically categorize your transactions (e.g., groceries, dining, travel, entertainment) based on:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Merchant names and Merchant Category Codes (MCCs)</li>
                <li>Transaction amounts and patterns</li>
                <li>Historical user behavior and feedback</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3">
                <strong>Limitation:</strong> Automated categorization may sometimes be incorrect or inconsistent, especially for merchants 
                that operate in multiple categories or have ambiguous names.
              </p>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">2.2 Spending Pattern Analysis</h3>
              <p className="text-foreground leading-relaxed mb-3">
                AI models analyze your transaction history to identify:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Recurring expenses and subscription payments</li>
                <li>Seasonal spending trends (e.g., increased travel in summer)</li>
                <li>Unusual or anomalous transactions that may indicate fraud</li>
                <li>Spending habits by time of day, day of week, or location</li>
              </ul>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">2.3 Credit Card Reward Optimization</h3>
              <p className="text-foreground leading-relaxed mb-3">
                AI algorithms match your spending patterns with publicly available credit card rewards program data to recommend:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Which card to use for specific merchants or categories to maximize rewards</li>
                <li>Opportunities to switch to a different card for better rewards alignment</li>
                <li>Alerts when you use a suboptimal card for a purchase</li>
                <li>Suggestions for new cards that may fit your spending profile</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3">
                <strong>Limitation:</strong> AI recommendations are based on available data at the time of analysis. Credit card terms, 
                rewards rates, and bonus categories can change without notice, and AI may not always have the most current information.
              </p>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">2.4 Budget Forecasting & Alerts</h3>
              <p className="text-foreground leading-relaxed mb-3">
                AI predicts future spending based on historical patterns to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Alert you when you're likely to exceed a budget</li>
                <li>Forecast monthly spending in various categories</li>
                <li>Suggest budget adjustments based on past behavior</li>
              </ul>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">2.5 Merchant Discovery & Location-Based Insights</h3>
              <p className="text-foreground leading-relaxed">
                If you enable location services, AI may:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Recommend nearby merchants where you can maximize rewards</li>
                <li>Identify location-based spending patterns (e.g., spending more when traveling)</li>
                <li>Suggest geofences for budget tracking at specific locations</li>
              </ul>
            </section>

            <Separator />

            <section id="ai-limitations">
              <h2 className="text-2xl font-semibold text-foreground mb-3">3. Limitations of AI-Generated Content</h2>
              <p className="text-foreground leading-relaxed mb-3 font-semibold">
                AI-GENERATED RECOMMENDATIONS AND INSIGHTS ARE NOT GUARANTEED TO BE ACCURATE, COMPLETE, OR SUITABLE FOR YOUR INDIVIDUAL CIRCUMSTANCES.
              </p>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">3.1 Data Limitations</h3>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li><strong>Incomplete Information:</strong> AI models are trained on the data available to them. If certain transactions are 
                  missing, incorrectly categorized, or if you use cash for purchases, the AI's analysis may be incomplete or skewed.
                </li>
                <li><strong>Outdated Information:</strong> Credit card terms, rewards programs, and merchant acceptance can change frequently. 
                  AI may not always have the most recent information when generating recommendations.
                </li>
                <li><strong>Data Quality Issues:</strong> If the underlying transaction data from your financial institution is inaccurate or 
                  inconsistent, AI outputs will reflect those errors.
                </li>
              </ul>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">3.2 Algorithmic Limitations</h3>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li><strong>Probabilistic Nature:</strong> Machine learning models produce probabilistic outputs, meaning they estimate the most 
                  likely outcome based on patterns, not certainties. There is always a margin of error.
                </li>
                <li><strong>Overfitting or Underfitting:</strong> AI models may sometimes overfit to your specific data (making overly specific 
                  recommendations that don't generalize) or underfit (failing to capture nuances in your behavior).
                </li>
                <li><strong>Bias in Training Data:</strong> If the data used to train AI models contains biases (e.g., favoring certain types 
                  of spending or demographics), those biases may be reflected in recommendations.
                </li>
              </ul>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">3.3 Context Awareness</h3>
              <p className="text-foreground leading-relaxed mb-3">
                AI does not have full context of your life circumstances, including:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Life events (e.g., job changes, moving, medical expenses) that may temporarily alter spending patterns</li>
                <li>Personal preferences or values (e.g., preferring to support local businesses over chain stores)</li>
                <li>Non-financial factors (e.g., customer service quality, ethical considerations) that may influence which card you choose to use</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3">
                AI recommendations are based purely on quantitative data and do not account for qualitative factors or personal values.
              </p>

              <h3 className="text-xl font-semibold text-foreground mb-2 mt-4">3.4 No Predictive Guarantees</h3>
              <p className="text-foreground leading-relaxed">
                AI cannot predict the future with certainty. Forecasts, budget predictions, and spending trend projections are estimates based on 
                historical data. Unexpected life changes, economic shifts, or other unforeseen events can make predictions inaccurate.
              </p>
            </section>

            <Separator />

            <section id="not-professional-advice">
              <h2 className="text-2xl font-semibold text-foreground mb-3">4. AI Does NOT Replace Professional Advice</h2>
              <p className="text-foreground leading-relaxed mb-3 font-semibold uppercase">
                AI-GENERATED INSIGHTS, RECOMMENDATIONS, AND PREDICTIONS DO NOT CONSTITUTE PROFESSIONAL FINANCIAL, INVESTMENT, LEGAL, OR TAX ADVICE.
              </p>
              <p className="text-foreground leading-relaxed mb-3">
                TrueSpend's AI is designed to provide informational insights and suggestions to help you make more informed decisions. However:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>AI cannot assess your overall financial situation, risk tolerance, or long-term goals</li>
                <li>AI does not consider legal, tax, or estate planning implications of financial decisions</li>
                <li>AI recommendations are generic and not tailored to complex individual circumstances</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3">
                Before making any significant financial decision based on AI-generated content, we strongly encourage you to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Conduct your own independent research and verification</li>
                <li>Consult with a qualified financial advisor, accountant, or attorney</li>
                <li>Review the terms and conditions of any financial products or services mentioned</li>
              </ul>
            </section>

            <Separator />

            <section id="user-responsibility">
              <h2 className="text-2xl font-semibold text-foreground mb-3">5. Your Responsibility When Using AI Recommendations</h2>
              <p className="text-foreground leading-relaxed mb-3">
                You acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li><strong>Independent Verification:</strong> You are solely responsible for independently verifying the accuracy and suitability 
                  of any AI-generated recommendations before acting on them.
                </li>
                <li><strong>Fact-Checking:</strong> You should cross-reference AI recommendations with official sources (e.g., credit card issuer 
                  websites, terms and conditions) to confirm current terms and offers.
                </li>
                <li><strong>Decision Autonomy:</strong> All financial decisions you make are your own. TrueSpend and its AI systems do not make 
                  decisions on your behalf.
                </li>
                <li><strong>Feedback:</strong> If you notice inaccuracies or errors in AI outputs, please report them to us at support@truespend.org 
                  so we can improve our models.
                </li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3 font-semibold">
                BY USING AI-GENERATED RECOMMENDATIONS, YOU ACCEPT ALL RISKS ASSOCIATED WITH RELYING ON SUCH CONTENT.
              </p>
            </section>

            <Separator />

            <section id="no-guarantees">
              <h2 className="text-2xl font-semibold text-foreground mb-3">6. No Guarantee of Savings or Rewards</h2>
              <p className="text-foreground leading-relaxed mb-3">
                TrueSpend does not guarantee that following AI recommendations will result in:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Increased credit card rewards or cashback earnings</li>
                <li>Cost savings or reduced spending</li>
                <li>Approval for credit cards or financial products suggested by the AI</li>
                <li>Achievement of specific financial goals or outcomes</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3">
                Actual results depend on numerous factors outside of TrueSpend's control, including:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>Changes in credit card terms or merchant acceptance</li>
                <li>Your individual spending behavior and discipline</li>
                <li>Economic conditions and market fluctuations</li>
                <li>Accuracy of the data you provide to the Service</li>
              </ul>
            </section>

            <Separator />

            <section id="model-updates">
              <h2 className="text-2xl font-semibold text-foreground mb-3">7. AI Model Updates & Improvements</h2>
              <p className="text-foreground leading-relaxed mb-3">
                TrueSpend continuously improves its AI models to enhance accuracy and relevance. This means:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>AI recommendations may change over time as models are retrained with new data</li>
                <li>Previously generated insights may become outdated or superseded by updated analyses</li>
                <li>New AI features and recommendation types may be introduced without prior notice</li>
              </ul>
              <p className="text-foreground leading-relaxed mt-3">
                We will notify you of significant changes to AI functionality through in-app notifications, email, or updates to this policy.
              </p>
            </section>

            <Separator />

            <section id="accuracy-disclaimers">
              <h2 className="text-2xl font-semibold text-foreground mb-3">8. Accuracy Disclaimers</h2>
              <p className="text-foreground leading-relaxed mb-3 font-semibold uppercase">
                TRUESPEND MAKES NO WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS, TIMELINESS, OR RELIABILITY OF AI-GENERATED 
                CONTENT. AI OUTPUTS ARE PROVIDED "AS IS" WITHOUT ANY GUARANTEE OF FITNESS FOR A PARTICULAR PURPOSE.
              </p>
              <p className="text-foreground leading-relaxed mb-3">
                You acknowledge that:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground">
                <li>AI can make mistakes, produce incorrect categorizations, or generate misleading recommendations</li>
                <li>AI may fail to detect fraudulent transactions or spending anomalies</li>
                <li>AI-predicted spending patterns may not materialize as forecasted</li>
                <li>TrueSpend is not liable for any losses, damages, or negative outcomes resulting from your reliance on AI-generated content</li>
              </ul>
            </section>

            <Separator />

            <section id="contact">
              <h2 className="text-2xl font-semibold text-foreground mb-3">9. Contact Information</h2>
              <p className="text-foreground leading-relaxed">
                If you have any questions, concerns, or feedback about TrueSpend's use of AI, please contact us at:
              </p>
              <p className="text-foreground leading-relaxed mt-3 font-medium">
                Email: <a href="mailto:support@truespend.org" className="text-primary hover:underline">support@truespend.org</a>
              </p>
              <p className="text-foreground leading-relaxed mt-3">
                We appreciate your feedback and continuously strive to improve the accuracy and usefulness of our AI systems.
              </p>
            </section>

            <Separator className="my-8" />

            <p className="text-sm text-muted-foreground text-center">
              © 2025 TrueSpend. All rights reserved.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}